services:
  postgres:
    image: postgres:latest
    container-name: postgresql
    ports: 5432:5432
    volume: var/lib/latest/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  fastapi-backend:
    build: ./fastapi-backend
    port: 8000:8000
    depends-on:

  react-frontend:
    build: ./react-frontend:
    port: 80:80

  adminer:
    image: adminer
    container-name: adminer
    port: 8080:8080
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
