services:
  postgres:
    image: postgres:latest
    container-name: postgresql
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/latest/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

  fastapi-backend:
    build: ./fastapi-backend:v1
    ports: 
      - 8000:8000
    networks:
      - app-network
    depends-on:
      - postgres

  react-frontend:
    build: ./react-frontend:v4
    ports: 
      - 80:80
    networks:
      - app-network

  adminer:
    image: adminer
    container-name: adminer:latest
    networks:
      - app-network
    ports: 
      - 8080:8080
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}

volumes:
  pgdata:

networks:
  app-network:


   

