services:
  postgres:
    image: postgres:latest
    container-name: postgresql
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/latest/postgres
    env_file:
      - .env
    #environment:
        #POSTGRES_DB: ${POSTGRES_DB}
        #POSTGRES_USER: ${POSTGRES_USER}
        #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

  fastapi-backend:
    build: ./backend
    container-name: fastapi-backend
    ports: 
      - "8000:8000"
    networks:
      - app-network
    depends-on:
      - postgres

  react-frontend:
    build: ./frontend
    container-name: react-frontend
    ports: 
      - "5173:5173"`
    networks:
      - app-network

  adminer:
    image: adminer
    container-name: adminer:latest
    networks:
      - app-network
    ports: 
      - "8080:8080"
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
        
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:


   

